In [1]:
import pandas as pd

In [2]:
url = 'https://es.wikipedia.org/wiki/Anexo:Finales_de_la_Copa_Mundial_de_F%C3%BAtbol'
df1 = pd.io.html.read_html(url)

In [5]:
df_soccer= df1[0]

In [6]:
df_soccer

Fecha           Campeón       Resultado        Subcampeón  \
0   30-07-1930           Uruguay             4:2         Argentina   
1   10-06-1934            Italia       2:1 (pr.)    Checoslovaquia   
2   19-06-1938            Italia             4:2           Hungría   
3   16-07-1950           Uruguay             2:1            Brasil   
4   04-07-1954  Alemania Federal             3:2           Hungría   
5   29-06-1958            Brasil             5:2            Suecia   
6   17-06-1962            Brasil             3:1    Checoslovaquia   
7   30-07-1966        Inglaterra       4:2 (pr.)  Alemania Federal   
8   21-06-1970            Brasil             4:1            Italia   
9   07-07-1974  Alemania Federal             2:1      Países Bajos   
10  25-06-1978         Argentina       3:1 (pr.)      Países Bajos   
11  11-07-1982            Italia             3:1  Alemania Federal   
12  29-06-1986         Argentina             3:2  Alemania Federal   
13  08-07-1990  Alemania Federal             1:0         Argentina   
14  17-07-1994            Brasil  0:0 (3:2 pen.)            Italia   
15  12-07-1998           Francia             3:0            Brasil   
16  30-06-2002            Brasil             2:0          Alemania   
17  09-07-2006            Italia  1:1 (5:3 pen.)           Francia   
18  11-07-2010            España       1:0 (pr.)      Países Bajos   
19  13-07-2014          Alemania       1:0 (pr.)         Argentina   
20  15-07-2018           Francia             4:2           Croacia   
21  18-12-2022         Argentina  3:3 (4:2 pen.)           Francia   
22  08-07-2026               NaN             NaN               NaN   

                              Estadio Espectadores       Localización  \
0                  Estadio Centenario       68 346         Montevideo   
1            Estadio Nacional del PNF       50 000               Roma   
2                     Stade Olympique       45 124           Colombes   
3                    Estadio Maracaná      199 150     Río de Janeiro   
4                     Wankdorfstadion       60 000              Berna   
5                     Estadio Råsunda       51 800              Solna   
6                    Estadio Nacional       68 679  Santiago de Chile   
7                  Estadio de Wembley       97 924            Londres   
8                      Estadio Azteca      107 412   Ciudad de México   
9                    Estadio Olímpico       75 200             Múnich   
10         Estadio Antonio V. Liberti       71 483       Buenos Aires   
11          Estadio Santiago Bernabéu       90 000             Madrid   
12                     Estadio Azteca      114 600   Ciudad de México   
13                   Estadio Olímpico       73 603               Roma   
14                  Estadio Rose Bowl       94 194           Pasadena   
15                    Stade de France       80 000        Saint-Denis   
16  Estadio Internacional de Yokohama       69 029           Yokohama   
17                   Estadio Olímpico       69 000             Berlín   
18                Estadio Soccer City       84 490      Johannesburgo   
19                   Estadio Maracaná       74 738     Río de Janeiro   
20          Estadio Olímpico Luzhnikí       78 011              Moscú   
21          Estadio Icónico de Lusail       88 966             Lusail   
22                                NaN          NaN                NaN   

         Notas  
0     [4]​[5]​  
1     [6]​[7]​  
2     [8]​[9]​  
3   [10]​[11]​  
4   [12]​[13]​  
5   [14]​[15]​  
6   [16]​[17]​  
7   [18]​[19]​  
8   [20]​[21]​  
9   [22]​[23]​  
10  [24]​[25]​  
11  [26]​[27]​  
12  [28]​[29]​  
13  [30]​[31]​  
14  [32]​[33]​  
15  [34]​[35]​  
16  [36]​[37]​  
17  [38]​[39]​  
18       [40]​  
19       [41]​  
20       [42]​  
21       [43]​  
22         NaN

In [7]:
df_soccer = df_soccer.drop('Notas', axis=1)

In [8]:
df_soccer

Fecha           Campeón       Resultado        Subcampeón  \
0   30-07-1930           Uruguay             4:2         Argentina   
1   10-06-1934            Italia       2:1 (pr.)    Checoslovaquia   
2   19-06-1938            Italia             4:2           Hungría   
3   16-07-1950           Uruguay             2:1            Brasil   
4   04-07-1954  Alemania Federal             3:2           Hungría   
5   29-06-1958            Brasil             5:2            Suecia   
6   17-06-1962            Brasil             3:1    Checoslovaquia   
7   30-07-1966        Inglaterra       4:2 (pr.)  Alemania Federal   
8   21-06-1970            Brasil             4:1            Italia   
9   07-07-1974  Alemania Federal             2:1      Países Bajos   
10  25-06-1978         Argentina       3:1 (pr.)      Países Bajos   
11  11-07-1982            Italia             3:1  Alemania Federal   
12  29-06-1986         Argentina             3:2  Alemania Federal   
13  08-07-1990  Alemania Federal             1:0         Argentina   
14  17-07-1994            Brasil  0:0 (3:2 pen.)            Italia   
15  12-07-1998           Francia             3:0            Brasil   
16  30-06-2002            Brasil             2:0          Alemania   
17  09-07-2006            Italia  1:1 (5:3 pen.)           Francia   
18  11-07-2010            España       1:0 (pr.)      Países Bajos   
19  13-07-2014          Alemania       1:0 (pr.)         Argentina   
20  15-07-2018           Francia             4:2           Croacia   
21  18-12-2022         Argentina  3:3 (4:2 pen.)           Francia   
22  08-07-2026               NaN             NaN               NaN   

                              Estadio Espectadores       Localización  
0                  Estadio Centenario       68 346         Montevideo  
1            Estadio Nacional del PNF       50 000               Roma  
2                     Stade Olympique       45 124           Colombes  
3                    Estadio Maracaná      199 150     Río de Janeiro  
4                     Wankdorfstadion       60 000              Berna  
5                     Estadio Råsunda       51 800              Solna  
6                    Estadio Nacional       68 679  Santiago de Chile  
7                  Estadio de Wembley       97 924            Londres  
8                      Estadio Azteca      107 412   Ciudad de México  
9                    Estadio Olímpico       75 200             Múnich  
10         Estadio Antonio V. Liberti       71 483       Buenos Aires  
11          Estadio Santiago Bernabéu       90 000             Madrid  
12                     Estadio Azteca      114 600   Ciudad de México  
13                   Estadio Olímpico       73 603               Roma  
14                  Estadio Rose Bowl       94 194           Pasadena  
15                    Stade de France       80 000        Saint-Denis  
16  Estadio Internacional de Yokohama       69 029           Yokohama  
17                   Estadio Olímpico       69 000             Berlín  
18                Estadio Soccer City       84 490      Johannesburgo  
19                   Estadio Maracaná       74 738     Río de Janeiro  
20          Estadio Olímpico Luzhnikí       78 011              Moscú  
21          Estadio Icónico de Lusail       88 966             Lusail  
22                                NaN          NaN                NaN

In [13]:
df2=pd.read_excel('/home/jameto/Documentos/cursoPython/datasets/poblacion.xlsx')
df2.shape

(5, 6)

In [10]:
df2

Continente  Densidad  Superficie   Población              País más poblado  \
0       Asia     86.88    43810000  4677291000         China (1.392.240.000)   
1     África     32.70    30370000  1110020000         Nigeria (191.205.000)   
2     Europa     70.00    10180000   801000000           Rusia (112.000.000)   
3    América     23.50    42330000  1094215000  Estados Unidos (330.028.000)   
4    Oceanía      4.25     9008500    40201000        Australia (27.240.000)   

              Ciudad más poblada  
0             Tokio (35.682.000)  
1          El Cairo (16.794.000)  
2             Moscú (18.940.000)  
3  Ciudad de México (22.577.000)  
4             Sídney (6.550.000)

In [11]:
df3 = pd.read_csv('/home/jameto/Documentos/cursoPython/datasets/poblacion.csv')

In [12]:
df3

Continente Densidad  Superficie      Población  \
0       Asia    86,88  43.810.000  4.677.291.000   
1     África     32,7  30.370.000  1.110.020.000   
2     Europa       70  10.180.000    801.000.000   
3    América     23,5  42.330.000  1.094.215.000   
4    Oceanía     4,25   9.008.500     40.201.000   

               País más poblado             Ciudad más poblada  
0         China (1.392.240.000)             Tokio (35.682.000)  
1         Nigeria (191.205.000)          El Cairo (16.794.000)  
2           Rusia (112.000.000)             Moscú (18.940.000)  
3  Estados Unidos (330.028.000)  Ciudad de México (22.577.000)  
4        Australia (27.240.000)             Sídney (6.550.000)

In [15]:
url2='https://es.wikipedia.org/wiki/Anexo:Pa%C3%ADses'
df4= pd.io.html.read_html(url2)

In [17]:
df4=df4[0]


In [19]:
df4=df4.drop('Ubicación',axis=1)
df4

Estado (forma oficial) Nombre común  \
0    República Islámica de Afganistán   Afganistán   
1                República de Albania      Albania   
2       República Federal de Alemania     Alemania   
3               Principado de Andorra      Andorra   
4                 República de Angola       Angola   
..                                ...          ...   
190   República Socialista de Vietnam      Vietnam   
191                República de Yemen        Yemen   
192               República de Yibuti       Yibuti   
193               República de Zambia       Zambia   
194             República de Zimbabue     Zimbabue   

                                     Forma de gobierno       Capital(es)  \
0                  República islámica presidencialista             Kabul   
1                              República parlamentaria            Tirana   
2                              República parlamentaria            Berlín   
3                             Monarquía constitucional  Andorra la Vieja   
4                           República presidencialista            Luanda   
..                                                 ...               ...   
190                    Estado socialista unipartidista             Hanói   
191  República presidencialista (Gobierno provisional)              Saná   
192                             República presidencial  Ciudad de Yibuti   
193                             República presidencial            Lusaka   
194                             República presidencial            Harare   

    Continente          Estatus ONU   Soberanía  \
0         Asia       Miembro (1946)  Reconocida   
1       Europa       Miembro (1955)  Reconocida   
2       Europa   Miembro (1973)[1]​  Reconocida   
3       Europa       Miembro (1993)  Reconocida   
4       África       Miembro (1976)  Reconocida   
..         ...                  ...         ...   
190       Asia       Miembro (1977)  Reconocida   
191       Asia  Miembro (1947)[34]​  Reconocida   
192     África       Miembro (1977)  Reconocida   
193     África       Miembro (1964)  Reconocida   
194     África       Miembro (1980)  Reconocida   

                                                 Notas  
0    Las Naciones Unidas actualmente reconocen a la...  
1                                                  NaN  
2    Estado miembro de la Unión Europea. Alemania e...  
3    Coprincipado con dos jefes de Estado, el presi...  
4                                                  NaN  
..                                                 ...  
190  Vietnam reclama la soberanía total de las isla...  
191                                                NaN  
192  Yibuti mantiene un conflicto fronterizo con Er...  
193                                                NaN  
194                                                NaN  

[195 rows x 8 columns]

# Tratamiento de datos con DataFrames

## Unión de DataFrames

In [35]:
import pandas as pd
import numpy as np

In [22]:
df_1 = pd.DataFrame({'Col1':['1','2','3'], 'clave':['a','b','c']})
df_1

Col1 clave
0    1     a
1    2     b
2    3     c

In [28]:
df_2 = pd.DataFrame({'col2':['4','5','6'], 'clave':['c','b','e']})
df_2

col2 clave
0    4     c
1    5     b
2    6     e

In [29]:
df_3=pd.DataFrame.merge(df_1,df_2)
df_3

Col1 clave col2
0    2     b    5
1    3     c    4

In [31]:
df_3=pd.DataFrame.merge(df_1,df_2, on='clave')
df_3

Col1 clave col2
0    2     b    5
1    3     c    4

In [32]:
df_4 = pd.DataFrame.merge(df_1,df_2, on='clave', how='left')
df_4

Col1 clave col2
0    1     a  NaN
1    2     b    5
2    3     c    4

In [33]:
df_5 = pd.DataFrame.merge(df_1,df_2, on='clave', how='right')
df_5

Col1 clave col2
0    3     c    4
1    2     b    5
2  NaN     e    6

In [34]:
df_6 = pd.DataFrame.merge(df_1,df_2, on='clave', how='outer')
df_6

Col1 clave col2
0    1     a  NaN
1    2     b    5
2    3     c    4
3  NaN     e    6

### Concatenacion de arrays, series y dataframes

In [36]:
arr1 = np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [37]:
np.concatenate([arr1,arr1])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [38]:
np.concatenate([arr1,arr1], axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])