In [3]:
import numpy as np
import pandas as pd
import random

## ejercicio 1
#### rearemos una lista de 50 valores aleatorios enteros entre los valores 0 y 100 Convertiremos esta lista en un dataframe con 5 filas y 10 columnas Filtraremos los datos del dataframe para visualizar solo los valores que sean mayores de 50

In [4]:
lista1 = [random.randint(0, 100) for _ in range(50)]
print(lista1)

[22, 14, 22, 97, 75, 46, 69, 52, 36, 84, 1, 71, 45, 68, 4, 32, 23, 6, 24, 21, 67, 75, 2, 7, 18, 87, 49, 8, 36, 3, 80, 19, 52, 29, 97, 52, 54, 34, 88, 40, 50, 46, 67, 85, 71, 39, 79, 78, 1, 36]


In [14]:
matriz_l=np.array(lista1).reshape(5,10)
print(matriz_l)

[[22 14 22 97 75 46 69 52 36 84]
 [ 1 71 45 68  4 32 23  6 24 21]
 [67 75  2  7 18 87 49  8 36  3]
 [80 19 52 29 97 52 54 34 88 40]
 [50 46 67 85 71 39 79 78  1 36]]


In [10]:
matriz = np.random.randint(0, 101, size=(5, 10))
print(matriz)

[[22 20 18 56 48 23 81 89 99 66]
 [52 33 51 67 41 15 49 59 38 48]
 [86 11 54  1 37 73 19 23 74 59]
 [81  5 25 21 31 79 16 54 30 47]
 [91 51 54 95 97 31 14 12 42 20]]


In [15]:
df1=pd.DataFrame(matriz)
df1


0   1   2   3   4   5   6   7   8   9
0  22  20  18  56  48  23  81  89  99  66
1  52  33  51  67  41  15  49  59  38  48
2  86  11  54   1  37  73  19  23  74  59
3  81   5  25  21  31  79  16  54  30  47
4  91  51  54  95  97  31  14  12  42  20

In [16]:
mask1=df1 >50

df2=df1[mask1]

In [17]:
df2

0     1     2     3     4     5     6     7     8     9
0   NaN   NaN   NaN  56.0   NaN   NaN  81.0  89.0  99.0  66.0
1  52.0   NaN  51.0  67.0   NaN   NaN   NaN  59.0   NaN   NaN
2  86.0   NaN  54.0   NaN   NaN  73.0   NaN   NaN  74.0  59.0
3  81.0   NaN   NaN   NaN   NaN  79.0   NaN  54.0   NaN   NaN
4  91.0  51.0  54.0  95.0  97.0   NaN   NaN   NaN   NaN   NaN

## Ejercicio 2
#### Crear 2 arrays con 9 números aleatorios enteros entre los valores 0 y 100 #Cambiar el formato de los arrays en una estructura de 3 filas por 3 columnas

#### Crear 2 dataframe con esos arrays

#### Concatenar esos 2 dataframes

In [19]:
arr1=np.random.randint(0,101, size=(3,3))
arr2=np.random.randint(0,101, size=(3,3))

In [24]:
print(arr1)

print(arr2)

[[20 32 97]
 [79 86 87]
 [26 10 99]]
[[ 0 65  4]
 [69 59 32]
 [54 17 86]]


In [25]:
df2_1=pd.DataFrame(arr1)
df2_2=pd.DataFrame(arr2)

In [29]:
df2_3=pd.concat([df2_1,df2_2])

In [30]:
df2_3

0   1   2
0  20  32  97
1  79  86  87
2  26  10  99
0   0  65   4
1  69  59  32
2  54  17  86

In [31]:
df2_4=pd.concat([df2_1,df2_2],axis=1)
df2_4

0   1   2   0   1   2
0  20  32  97   0  65   4
1  79  86  87  69  59  32
2  26  10  99  54  17  86